otel:
  name: lgtm-based-service
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:grpc}
  logs:
    level: ${OTEL_LOG_LEVEL:info}
  metrics:
    enabled: ${OTEL_METRICS_ENABLED:true}
    prometheus:
      endpoint: ${OTEL_PROMETHEUS_ENDPOINT:/metrics}
  traces:
    enabled: ${OTEL_TRACES_ENABLED:true}
    sampler: ${OTEL_TRACES_SAMPLER:parentbased_always_on}
    exporter: ${OTEL_TRACES_EXPORTER:otlp}
